# Generated by Django 5.0.7 on 2024-07-15 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anime', '0002_anime_episodes_anime_episodes_aired_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='anime',
            name='image',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='anime',
            name='episodes_aired',
            field=models.IntegerField(default=12),
        ),
        migrations.AlterField(
            model_name='anime',
            name='kind',
            field=models.TextField(default='TV'),
        ),
    ]
